package cachevg.db.command;

public enum CommandNames {
    PUT, REMOVE, GET, KEYS, PING, LPUSH, RPUSH, LPOP, RPOP, AND, XOR, OR, NOT, BIT_SET, BIT_GET,
    LIST, LENGTH, GETIND, STRLEN, SUBSTR, SETRNG, APPEND, PREPEND, REVERSE, ZEROCNT, ONECNT, FLIP,
    INCRBY, INCRBYFLOAT, ISEVEN, ISODD, IS2POW
}
