package cachevg.db.command;

public enum CommandNames {
    PUT, REMOVE, GET, KEYS, PING, LPUSH, RPUSH, LPOP, RPOP, AND, XOR, OR, NOT, SBIT, GBIT,
    LIST, LENGTH, GETIND, STRLEN, SUBSTR, SETRNG, APPEND, PREPEND, REVERSE, ZEROCNT, ONECNT, FLIP,
    INCRBY, INCRBYFLOAT, EVEN, ODD, POW2
}
